title: Stitch Documentation

# Enable Jekyll emoji plugin, so that you could write emoji same way you do on Github
plugins:
  - jemoji

theme: jekyll-theme-primer

collections_dir: ./_collections
collections:
  exports:
    output: true
  edit:
    output: true

# Some constants
github_repo: https://github.com/SmokedSalmon/Stitch/
sidebar_excludes:
  - README.md
  - about.md
  - examples.md
  - markdown_page_example.md
